name: Build Kernel
on:
  workflow_dispatch:

jobs:
  Build-Kernel:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - name: Build Kernel
      uses: dabao1955/kernel_build_action@main
      with:
          kernel-url: https://github.com/Asimplayz1/kernel-xiaomi-sm8350.git
          kernel-dir: Kernelicious-KSUN
          kernel-branch: Kernelicious-KSUN
          config: sm8350_defconfig  # Replace with correct defconfig
          arch: arm64
          aosp-gcc: true
          aosp-clang: true
          ksu: true
          ksu-version: main
          android-version: 14  # Updated for Android 14
          aosp-clang-version: r383902
          disable-lto: true
          anykernel3: true
